name: Run Playwright Tests

# Определение триггеров для запуска workflow
on:
  push:
    branches:
      - master 
    paths-ignore:
      - '**.md' # Игнорирование изменений в markdown-файлах
  pull_request:
    branches: master 
    paths-ignore:
      - '**.md' # Игнорирование изменений в markdown-файлах

jobs:
  test:
    timeout-minutes: 20 # Увеличенное ограничение времени выполнения job
    runs-on: ${{ matrix.os }}

    # Определение матрицы для запуска тестов на разных операционных системах и браузерах
    strategy:
      fail-fast: false # Отключаем поведение fail-fast, чтобы все тесты выполнялись до конца
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] # Запуск на Ubuntu, Windows и macOS
        browser: [chromium, firefox] # Браузеры для тестирования на всех ОС
        include:
          - os: ubuntu-latest
            browser: webkit # Добавляем webkit только для Ubuntu
          - os: macos-latest
            browser: webkit # Добавляем webkit для macOS

    steps:
      # Шаги тестирования (все остаются без изменений)
      - name: Install dependencies
        # остальные шаги установки и выполнения тестов здесь
      # Установка зависимостей, кэширование, запуск тестов и т.д.

  # Публикация Allure отчета на GitHub Pages, даже если некоторые тесты провалились
  deploy:
    needs: test # Зависимость от завершения всех тестов
    runs-on: ubuntu-latest
    if: always() # Гарантирует выполнение deploy даже при ошибках в тестах
    permissions:
      pages: write # Права на запись для публикации на GitHub Pages
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1 # Публикует отчет на GitHub Pages
