name: Run Playwright Tests

# Определение триггеров для запуска workflow
on:
  push:
    branches:
      - master 
    paths-ignore:
      - '**.md' # Игнорирование изменений в markdown-файлах
  pull_request:
    branches: master 
    paths-ignore:
      - '**.md' # Игнорирование изменений в markdown-файлах

jobs:
  test:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}

    # Определение матрицы для запуска тестов на разных операционных системах и браузерах
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] # Запуск на Ubuntu, Windows и macOS
        browser: [chromium, firefox] # Браузеры для тестирования
        include:
          - os: macos-latest
            browser: webkit # Добавление Safari (webkit) для macOS

    steps:
      # Шаг 1: Клонирование репозитория
      - uses: actions/checkout@v4

      # Шаг 2: Настройка Node.js для использования LTS-версии
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Шаг 3: Установка зависимостей с использованием Yarn
      - name: Install dependencies
        run: yarn install

      # Шаг 4: Установка браузеров Playwright
      # Используем --with-deps на Linux и macOS для установки дополнительных зависимостей
      - name: Install Playwright Browsers
        run: |
          if [ "${{ runner.os }}" == "Linux" ] || [ "${{ runner.os }}" == "macOS" ]; then
            npx playwright install --with-deps
          else
            npx playwright install
          fi
        shell: bash # Указываем bash, чтобы избежать проблем с синтаксисом на Windows

      # Шаг 5: Запуск тестов Playwright для указанного браузера
      # Используем дополнительный вывод результатов (--reporter=list) для упрощения отладки
      - name: Run Playwright tests
        run: |
          yarn playwright test --project=${{ matrix.browser }} --reporter=list

      # Шаг 6: Загрузка отчетов Allure как артефактов для дальнейшего анализа
      - name: Upload Allure Report
        if: ${{ !cancelled() }} # Выполняется только если job не был отменен
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ matrix.os }}-${{ matrix.browser }} # Уникальное имя для каждого артефакта
          path: allure-results/ # Путь к папке с отчетами
          retention-days: 1 # Хранение артефактов в течение 1 дня
