name: Run Playwright Tests

# Определение триггеров для запуска workflow
on:
  push:
    branches:
      - master 
    paths-ignore:
      - '**.md' # Игнорирование изменений в markdown-файлах
  pull_request:
    branches: master 
    paths-ignore:
      - '**.md' # Игнорирование изменений в markdown-файлах

jobs:
  test:
    timeout-minutes: 10 # Ограничение времени выполнения job
    runs-on: ${{ matrix.os }}

    # Определение матрицы для запуска тестов на разных операционных системах и браузерах
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] # Запуск на Ubuntu, Windows и macOS
        browser: [chromium, firefox] # Браузеры для тестирования
        include:
          - os: macos-latest
            browser: webkit # Добавление Safari (webkit) для macOS

    steps:
      # Шаг 1: Клонирование репозитория
      - uses: actions/checkout@v4

      # Шаг 2: Настройка Node.js для использования LTS-версии
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Шаг 3: Установка зависимостей без загрузки браузеров Playwright
      - name: Install dependencies without downloading browsers
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1 # Переменная окружения для пропуска загрузки браузеров
        run: yarn install # Устанавливаем зависимости проекта

      # Шаг 4: Установка только нужного браузера
      - name: Install specific Playwright Browser
        run: |
          # Проверяем браузер, указанный в матрице, и устанавливаем только его
          if [ "${{ matrix.browser }}" == "chromium" ]; then
            npx playwright install chromium
          elif [ "${{ matrix.browser }}" == "firefox" ]; then
            npx playwright install firefox
          elif [ "${{ matrix.browser }}" == "webkit" ]; then
            npx playwright install webkit
          fi
        shell: bash # Указываем bash, чтобы избежать проблем с синтаксисом на Windows

      # Шаг 5: Запуск тестов Playwright для указанного браузера
      - name: Run Playwright tests
        run: |
          yarn playwright test --project=${{ matrix.browser }} --reporter=list # Запуск тестов с выводом детализированного лога

      # Шаг 6: Генерация отчета Allure
      - name: Generate Allure Report
        if: always() # Выполняется независимо от результата предыдущих шагов
        run: |
          # Используем yarn для генерации отчета Allure и сохранения его в allure-report
          yarn run allure generate allure-results --clean -o allure-report

      # Шаг 7: Загрузка отчета Allure как артефакта
      - name: Upload Allure Report
        if: always() # Выполняется независимо от результата предыдущих шагов
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ matrix.os }}-${{ matrix.browser }} # Уникальное имя для каждого артефакта
          path: allure-report/ # Путь к папке с отчетами
          retention-days: 1 # Хранение артефактов в течение 1 дня

      # Шаг 8: Публикация Allure отчета на GitHub Pages
      - name: Publish Allure Report to Pages
        uses: mikepenz/allure-report-action@v1 # Используем корректную версию v1
        if: always() # Выполняется независимо от результата предыдущих шагов
        with:
          report_paths: allure-report # Путь к сгенерированному отчету Allure для публикации на GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Токен для доступа и публикации на GitHub Pages
