name: Run Playwright Tests

on:
  push:
    branches:
      - master 
    paths-ignore:
    - '**.md' 
  pull_request:
    branches: master 
    paths-ignore:
      - '**.md' 

jobs:
  test:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        browser: [chromium, firefox]
        include:
          - os: macos-latest
            browser: webkit 

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: yarn install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          if [ "${{ matrix.browser }}" = "webkit" ]; then
            yarn playwright test --project=safari;
          else
            yarn playwright test --project=${{ matrix.browser }};
          fi

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ matrix.os }}-${{ matrix.browser }}
          path: playwright-report/
          retention-days: 1
